# Generated by Django 4.2.27 on 2026-03-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('csex', models.CharField(default='F', max_length=1)),
                ('cbirthday', models.DateField(blank=True, null=True)),
                ('cemail', models.CharField(max_length=100)),
                ('cphone', models.CharField(max_length=50)),
                ('caddr', models.CharField(max_length=255)),
            ],
        ),
    ]
